export const states: Record<string, { name: string; costFactor: number }> = {
  'AL': { name: 'Alabama', costFactor: 0.9 },
  'AK': { name: 'Alaska', costFactor: 1.4 },
  'AZ': { name: 'Arizona', costFactor: 1.0 },
  'AR': { name: 'Arkansas', costFactor: 0.9 },
  'CA': { name: 'California', costFactor: 1.3 },
  'CO': { name: 'Colorado', costFactor: 1.1 },
  'CT': { name: 'Connecticut', costFactor: 1.2 },
  'DE': { name: 'Delaware', costFactor: 1.1 },
  'FL': { name: 'Florida', costFactor: 1.1 },
  'GA': { name: 'Georgia', costFactor: 1.0 },
  'HI': { name: 'Hawaii', costFactor: 1.4 },
  'ID': { name: 'Idaho', costFactor: 0.9 },
  'IL': { name: 'Illinois', costFactor: 1.1 },
  'IN': { name: 'Indiana', costFactor: 0.9 },
  'IA': { name: 'Iowa', costFactor: 0.9 },
  'KS': { name: 'Kansas', costFactor: 0.9 },
  'KY': { name: 'Kentucky', costFactor: 0.9 },
  'LA': { name: 'Louisiana', costFactor: 0.9 },
  'ME': { name: 'Maine', costFactor: 1.0 },
  'MD': { name: 'Maryland', costFactor: 1.2 },
  'MA': { name: 'Massachusetts', costFactor: 1.3 },
  'MI': { name: 'Michigan', costFactor: 1.0 },
  'MN': { name: 'Minnesota', costFactor: 1.0 },
  'MS': { name: 'Mississippi', costFactor: 0.8 },
  'MO': { name: 'Missouri', costFactor: 0.9 },
  'MT': { name: 'Montana', costFactor: 0.9 },
  'NE': { name: 'Nebraska', costFactor: 0.9 },
  'NV': { name: 'Nevada', costFactor: 1.1 },
  'NH': { name: 'New Hampshire', costFactor: 1.1 },
  'NJ': { name: 'New Jersey', costFactor: 1.3 },
  'NM': { name: 'New Mexico', costFactor: 0.9 },
  'NY': { name: 'New York', costFactor: 1.4 },
  'NC': { name: 'North Carolina', costFactor: 1.0 },
  'ND': { name: 'North Dakota', costFactor: 0.9 },
  'OH': { name: 'Ohio', costFactor: 1.0 },
  'OK': { name: 'Oklahoma', costFactor: 0.9 },
  'OR': { name: 'Oregon', costFactor: 1.1 },
  'PA': { name: 'Pennsylvania', costFactor: 1.1 },
  'RI': { name: 'Rhode Island', costFactor: 1.2 },
  'SC': { name: 'South Carolina', costFactor: 0.9 },
  'SD': { name: 'South Dakota', costFactor: 0.9 },
  'TN': { name: 'Tennessee', costFactor: 0.9 },
  'TX': { name: 'Texas', costFactor: 1.0 },
  'UT': { name: 'Utah', costFactor: 1.0 },
  'VT': { name: 'Vermont', costFactor: 1.1 },
  'VA': { name: 'Virginia', costFactor: 1.1 },
  'WA': { name: 'Washington', costFactor: 1.2 },
  'WV': { name: 'West Virginia', costFactor: 0.8 },
  'WI': { name: 'Wisconsin', costFactor: 1.0 },
  'WY': { name: 'Wyoming', costFactor: 0.9 }
};